### ISSUE TITLE
question about proxy failure

### ISSUE THREAD

**Issue by cheneydeng** [github/glb-director#59]
Glad to read your blog post about "Github Load Balance",That post said GLB will not disrupt any connection in any condition,in my opinion,the addition and remove of proxy is ok,because the existence connection data flow will be handled by the old primary(the new secondary),but what if the primary fail,I don't see how the primary sync with secondary about connection state information,will the connection be terminated on secondary?

**Comment by theojulienne** [comment]
> That post said GLB will not disrupt any connection in any condition

To clarify, if a machine fails, the connections that are terminated on that machine will obviously fail, because the state in the Linux kernel for the connection and the application level state in haproxy, nginx, or whatever service is also gone. GLB doesn't prevent this.

What GLB does is ensure that on a single host failure, no _other_ connections are disrupted as connections are redistributed. In addition, if the primary is _drained_ rather than hard-failed, GLB will gracefully drain it of connections, rather than breaking any of them.

**Comment by cheneydeng** [comment]
> To clarify, if a machine fails, the connections that are terminated on that machine will obviously fail, because the state in the Linux kernel for the connection and the application level state in haproxy, nginx, or whatever service is also gone. GLB doesn't prevent this.

Thanks for clarifying that.
